<a href="https://colab.research.google.com/github/JuliaKurz/2023-MATH-242-Projects/blob/main/Gram_Schmidt_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

**Implement Gram Schmidt on 4 vectors**

In [23]:
r1 = np.array([3,0,3,0])
r2 = np.array([3,2,3,3])
r3 = np.array([-7,-4,-5,-6])
r4 = np.array([-7,-3,-11,2])
print(r1)
print(r2)
print(r3)
print(r4)

[3 0 3 0]
[3 2 3 3]
[-7 -4 -5 -6]
[ -7  -3 -11   2]


Process **Vectors**

In [24]:
t1 = r1
m1 = np.sqrt(t1.dot(t1))
u1  = (1/m1)*t1
print(u1)

[0.70710678 0.         0.70710678 0.        ]


In [25]:
t2 = r2 - r2.dot(u1)*u1
m2 = np.sqrt(t2.dot(t2))
u2 = (1/m2)*t2
print(u2)

[-1.23168186e-16  5.54700196e-01 -1.23168186e-16  8.32050294e-01]


In [26]:
t3 = r3 - r3.dot(u1)*u1 -r3.dot(u2)*u2
m3 = np.sqrt(t3.dot(t3))
u3 = (1/m3)*t3
print(u3)

[-7.07106781e-01 -3.14018492e-16  7.07106781e-01 -6.28036983e-16]


In [27]:
t4 = r4 - r4.dot(u1)*u1 -r4.dot(u2)*u2- r4.dot(u3)*u3
m4 = np.sqrt(t4.dot(t4))
u4 = (1/m4)*t4
print(u4)

[ 0.         -0.83205029  0.          0.5547002 ]


In [28]:
#Sanity Check
print("the side of u1 =", np.sqrt(u1.dot(u1)))
print("the side of u2 =", np.sqrt(u2.dot(u2)))
print("the side of u3 =", np.sqrt(u3.dot(u3)))
print("the side of u4 =", np.sqrt(u4.dot(u4)))

the side of u1 = 1.0
the side of u2 = 1.0
the side of u3 = 0.9999999999999999
the side of u4 = 1.0


Write r1, r2, r3, and r4 in terms of u1, u2,u3,u4

In [29]:
print("r2=", r2.dot(u1), "u1+", r2.dot(u2), "u2+", r2.dot(u3), "u3+", r2.dot(u4), "u4")

r2= 4.242640687119286 u1+ 3.6055512754639887 u2+ -2.3282001602705925e-15 u3+ -4.218847493575595e-15 u4


In [30]:
print("r1=", r1.dot(u1), "u1+", r1.dot(u2), "u2+", r1.dot(u3), "u3+", r1.dot(u4), "u4")

r1= 4.242640687119286 u1+ -7.390091155360101e-16 u2+ 0.0 u3+ 0.0 u4


In [31]:
print("r3=", r3.dot(u1), "u1+", r3.dot(u2), "u2+", r3.dot(u3), "u3+", r3.dot(u4), "u4")

r3= -8.485281374238571 u1+ -7.211102550927977 u2+ 1.4142135623730991 u3+ 8.43769498715119e-15 u4


In [32]:
print("r4=", r4.dot(u1), "u1+", r4.dot(u2), "u2+", r4.dot(u3), "u3+", r4.dot(u4), "u4")

r4= -12.727922061357855 u1+ 2.220446049250313e-15 u2+ -2.8284271247461903 u3+ 3.6055512754639896 u4
