<a href="https://colab.research.google.com/github/JuliaKurz/2023-MATH-242-Projects/blob/main/Gram_Schmidt_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

**Implement Gram Schmidt on 4 vectors**

In [10]:
r1 = np.array([3,0,3,0])
r2 = np.array([3,2,3,3])
r3 = np.array([-7,-4,-5,-6])
r4 = np.array([-7,-3,-11,2])
print(r1)
print(r2)
print(r3)
print(r4)

[3 0 3 0]
[3 2 3 3]
[-7 -4 -5 -6]
[ -7  -3 -11   2]


**Magnitude of Vectors**

In [15]:
#magnitude of r1
m1 = np.sqrt(r1.dot(r1))
print(m1)

4.242640687119285


In [16]:
#magnitude of r2
m2 = np.sqrt(r2.dot(r2))
print(m2)

5.5677643628300215


In [17]:
#magnitude of r3
m3 = np.sqrt(r3.dot(r3))
print(m3)

11.224972160321824


In [18]:
#magnitude of r4
m4 = np.sqrt(r4.dot(r4))
print(m4)

13.527749258468683


Process **Vectors**

In [25]:
t1 = r1
u1  = (1/m1)*t1
print(u1)

[0.70710678 0.         0.70710678 0.        ]


In [38]:
t2 = r2 - r2.dot(u1)*u1
u2 = (1/m2)*t2
print(u2)

[-7.97607767e-17  3.59210604e-01 -7.97607767e-17  5.38815906e-01]


In [37]:
#Sanity Check
print("the side of u1 =", np.sqrt(u1.dot(u1)))
print("the side of u2 =", np.sqrt(u2.dot(u2)))
print("the side of u3 =", np.sqrt(u3.dot(u3)))
print("the side of u4 =", np.sqrt(u4.dot(u4)))

the side of u1 = 1.0
the side of u2 = 0.6475761258027333
the side of u3 = 0.5895069967765166


NameError: ignored